import ClientWidgetCount from "../ClientDashboard/ClientWidget/ClientWidgetCount";

export const vendorWidgetData = [
  {
    id: 2,
    cardColor: "secondary",
    label: "Paid Invoices",
    badge: "ri-arrow-right-down-line",
    badgeClass: "danger",
    percentage: "",
    counter: "",
    link: "View all",
    bgcolor: "success",
    icon: "bx bx-dollar-circle",
    decimals: 0,
    prefix: "",
    separator: ",",
    suffix: "",
    route: "/estimateList",
    name: "paidInvoices",
    component: ClientWidgetCount,
  },
  {
    id: 3,
    cardColor: "primary",
    label: "Pending Invoices",
    badge: "ri-arrow-right-down-line",
    badgeClass: "danger",
    percentage: "",
    counter: "",
    link: "View all",
    bgcolor: "warning",
    icon: "mdi mdi-flag-triangle",
    decimals: 0,
    prefix: "",
    separator: ",",
    suffix: "",
    route: "/estimateList",
    name: "pendingInvoices",
    component: ClientWidgetCount,
  },
  {
    id: 4,
    cardColor: "secondary",
    label: "Pending Payment Invoices",
    badge: "bx bx-dollar-circle",
    badgeClass: "danger",
    percentage: "",
    counter: "",
    link: "View all",
    bgcolor: "success",
    icon: "bx bx-dollar-circle",
    decimals: 0,
    prefix: "",
    separator: ",",
    suffix: "",
    route: "/estimateList",
    name: "pendingPaymentInvoices",
    component: ClientWidgetCount,
  },
  {
    id: 5,
    cardColor: "warning",
    label: "Rejected Invoices",
    badge: "ri-arrow-right-down-line",
    badgeClass: "danger",
    percentage: "",
    counter: "",
    link: "View all",
    bgcolor: "danger",
    icon: "bx bx-dollar-circle",
    decimals: 0,
    prefix: "",
    separator: ",",
    suffix: "",
    route: "/estimateList",
    name: "rejectedInvoices",
    component: ClientWidgetCount,
  },
  {
    id: 6,
    cardColor: "info",
    label: "Total Invoices",
    badge: "ri-arrow-right-down-line",
    badgeClass: "danger",
    percentage: "",
    counter: "",
    link: "View all",
    bgcolor: "primary",
    icon: "bx bx-dollar-circle",
    decimals: 0,
    prefix: "",
    separator: ",",
    suffix: "",
    route: "/estimateList",
    name: "totalInvoices",
    component: ClientWidgetCount,
  },
  {
    id: 7,
    cardColor: "success",
    label: "Available For Invoicing",
    badge: "ri-arrow-right-down-line",
    badgeClass: "danger",
    percentage: "",
    counter: "",
    link: "View all",
    bgcolor: "success",
    icon: "bx bx-calendar-alt",
    decimals: 0,
    prefix: "",
    separator: ",",
    suffix: "",
    route: "/estimateList",
    name: "availableForInvoicing",
    component: ClientWidgetCount,
  },
  {
    id: 8,
    cardColor: "danger",
    label: "Rejected Estimates",
    badge: "ri-arrow-right-down-line",
    badgeClass: "danger",
    percentage: "",
    counter: "",
    link: "View all",
    bgcolor: "danger",
    icon: "bx bx-calendar-alt",
    decimals: 0,
    prefix: "",
    separator: ",",
    suffix: "",
    route: "/estimateList",
    name: "rejectedEstimates",
    component: ClientWidgetCount,
  },
  {
    id: 9,
    cardColor: "dark",
    label: "All Estimates",
    badge: "ri-arrow-right-down-line",
    badgeClass: "danger",
    percentage: "",
    counter: "",
    link: "View all",
    bgcolor: "primary",
    icon: "bx bx-calendar-alt",
    decimals: 0,
    prefix: "",
    separator: ",",
    suffix: "",
    route: "/estimateList",
    name: "allEstimates",
    component: ClientWidgetCount,
  },
  {
    id: 10,
    cardColor: "warning",
    label: "Need Quotes",
    badge: "ri-arrow-right-down-line",
    badgeClass: "danger",
    percentage: "",
    counter: "",
    link: "View all",
    bgcolor: "warning",
    icon: "bx bx-calendar-alt",
    decimals: 0,
    prefix: "",
    separator: ",",
    suffix: "",
    route: "/estimateList",
    name: "needQuote",
    component: ClientWidgetCount,
  },
];

export const tripCategories = [
  "Completed",
  "In Progress",
  "Return Trip Required",
  "Scheduled",
];
