import ClientWidgetCount from "./ClientWidget/ClientWidgetCount";

export const clientWidgetData = [
  {
    id: 2,
    cardColor: "secondary",
    label: "Pending Active Quotes",
    badge: "ri-arrow-right-down-line",
    badgeClass: "danger",
    percentage: "",
    counter: "",
    link: "View all",
    bgcolor: "info",
    icon: "bx bx-dollar-circle",
    decimals: 0,
    prefix: "",
    separator: ",",
    suffix: "",
    route: "/estimateList",
    name: "Pending",
    component: ClientWidgetCount,
  },
  {
    id: 3,
    cardColor: "primary",
    label: "Rejected Active Quotes",
    badge: "ri-arrow-right-down-line",
    badgeClass: "danger",
    percentage: "",
    counter: "",
    link: "View all",
    bgcolor: "danger",
    icon: "mdi mdi-flag-triangle",
    decimals: 0,
    prefix: "",
    separator: ",",
    suffix: "",
    route: "/estimateList",
    name: "Rejected",
    component: ClientWidgetCount,
  },
  {
    id: 4,
    cardColor: "secondary",
    label: "Approved Active Quotes",
    badge: "ri-arrow-right-down-line",
    badgeClass: "danger",
    percentage: "",
    counter: "",
    link: "View all",
    bgcolor: "warning",
    icon: "bx bx-calendar-alt",
    decimals: 0,
    prefix: "",
    separator: ",",
    suffix: "",
    route: "/estimateList",
    name: "Approved",
    component: ClientWidgetCount,
  },
];

export const clientInvoiceWidgetData = [
  {
    id: 1,
    cardColor: "primary",
    label: "Paid Invoices",
    badge: "ri-arrow-right-up-line",
    badgeClass: "success",
    percentage: "",
    counter: "",
    link: "View all",
    bgcolor: "primary",
    icon: "bx bx-dollar-circle",
    decimals: 0,
    prefix: "$",
    suffix: ".00",
    route: "/invoiceList",
    name: "total",
    main: "Approved for payment",
    component: ClientWidgetCount,
  },
  {
    id: 2,
    cardColor: "secondary",
    label: "Average Invoice Amount",
    badge: "ri-arrow-right-down-line",
    badgeClass: "danger",
    percentage: "",
    counter: "",
    link: "View all",
    bgcolor: "info",
    icon: "bx bx-dollar-circle",
    decimals: 0,
    prefix: "$",
    separator: ",",
    suffix: ".00",
    route: "/invoiceList",
    name: "average",
    main: "Approved for payment",
    component: ClientWidgetCount,
  },
];
