export const CONSTANT = {
  GET_TENANT_DROPDOWN: "Get_Tenant_Dropdown",
  BILLING_ADDRESS: "Billing",
  SHIPPING_ADDRESS: "Shipping",
  CANCEL_ESTIMATE: "Cancel_Estimate",
  UPDATE_VENDOR_INFO: "Update_Vendor_Business_Info",
  UPDATE_TECHNICIAN_INFO: "Update_Technician_User",
  PAYMENT_TYPE: ["ACH", "Cash", "Credit Card", "Net Terms", "Paypal", "Wire"],
  TERM_NET_TYPE: ["Due on Receipt", "Net 15", "Net 30", "Net 60"],
  GET_SUBCONTRACTOR_DROPDOWN: "Get_Vendor_Dropdown",
  GET_STORE_DROPDOWN: "Get_Store_Dropdown",
  EDIT_WORK_REQUEST_DETAILS: "Edit_Service_Request",
  ACCEPT_SERVICE_REQUEST: "Accept_Service_Request",
  REJECT_SERVICE_REQUEST: "Reject_Service_Request",
  REJECTED: "Rejected",
  CREATE_WORK_ORDER: "Create_Workorder",
  GET_CLIENT_DROPDOWN: "Get_Client_Dropdown",
  WORK_ORDER_ASSIGN_VENDOR: "Work_Order_Assign_Vendor",
  WORK_ORDER_ASSIGN_TECHNICIAN: "Work_Order_Assign_Technician",
  CREATE_TRIP: "Create_Trip",
  STORE_USER_UPDATE: "Store_User_Update",
  CLIENT_USER_UPDATE: "Client_User_Update",
  COMPLETED: "Completed",
  SCHEDULED: "Scheduled",
  UPDATE_TRADE_ISSUE: "Update_Trades_Issue",
  SHOW_WORK_ORDERS: "Store_Order_List",
  TRIPS_LIST: "Trip_List",
  EDIT_WORK_ORDER: "Edit_Workorder",
  CREATE_ESTIMATE: "Create_Estimate",
  TENANT_USER_UPDATE: "Tenant_User_Update",
  ADD_CLIENT: "Create_Client",
  ADD_TENANT: "Create_Tenant",
  ADD_STORE: "Create_Store",
  ADD_CORPORATE_USER: "Create_Tenant_User",
  ADD_CLIENT_USER: "Create_Client_User",
  ADD_STORE_USER: "Create_Store_User",
  ADD_VENDOR: "Create_Vendor",
  ADD_TECHNICIAN: "Create_Technician",
  ADD_SERVICE_REQUEST: "Create_Service_Request",
  ADD_TRADE: "Create_Trades",
  VENDOR_LIST: "Vendor_List",
  TECHNICIAN_LIST: "Technician_List",
  ADD_TRADE_ISSUE: "Create_Trades_Issue",
  IMPORT_STORE_USERS: "Import_Store_Users",
  IMPORT_CLIENT_USERS: "Import_Client_Users",
  IMPORT_STORES: "Import_Store",
  TRIP_CHARGES_TYPE: ["Regular Trip Charge", "Emergency Trip Charge"],
  RATE_TYPE: [
    "Regular Rate",
    "After Hours Rate",
    "Weekend Rate",
    "Holiday Rate",
    "Emergency Rate",
    "Weekend Emergency Rate",
  ],
  PERMISSION_TYPE: ["Enabled", "Disabled", "All"],
  ESTIMATE_ACCEPT: "Approve_Estimate",
  ESTIMATE_DECLINE: "Reject_Estimate",
  APPROVED: "Approved",
  REVISE_ESTIMATE: "Revise_Estimate",
  PENDING: "Pending",
  INCURRED: "Incurred",
  ESTIMATE: "Estimate",
  DRAFT: "Draft",
  GENERATE_INVOICE: "Generate_Invoice",
  CREATE_INVOICE: "Create_Invoice",
  ESTIMATE_LIST: "Estimate_List",
  INVOICE_LIST: "Invoice_List",
  EXPENSE_LIST: "Expense_List",
  CREATE_EXPENSE: "Create_Expense",
  INVOICE_ACCEPT: "Approve_Invoice",
  INVOICE_DECLINE: "Reject_Invoice",
  REVISE_INVOICE: "Revise_Invoice",
  INVOICE: "Invoice",
  APPROVED_FOR_PAYMENT: "Approved for payment",
  PURCHASE_BY: [
    { name: "Stock", value: "Stock" },
    { name: "Purchased", value: "Vendor" },
  ],
  CREATE_RETURN_TRIP: "Create_Return_Trip",
  RETURN_TRIP_REQUIRED: "Return Trip Required",
  SUPER_ADMIN: "SUPER_ADMIN",
  IMPERSONATE_USER: "Reauth",
  ROLE_CORPORATE: "ROLE_CORPORATE",
  ROLE_CLIENT: "ROLE_CLIENT",
  ROLE_STOREMANAGER: "ROLE_STOREMANAGER",
  ROLE_ADMIN: "ROLE_ADMIN",
  ROLE_STOREUSER: "ROLE_STOREUSER",
  ROLE_VENDOR: "Vendor",
  ROLE_TECHNICIAN: "ROLE_TECHNICIAN",
  TRIP_STATUS: [
    {
      name: "Completed",
    },
    {
      name: "In Progress",
    },
    {
      name: "Return Trip Required",
    },
    {
      name: "Scheduled",
    },
  ],
  WORK_ORDER_STATUS: [
    {
      name: "New",
    },
    {
      name: "Current",
    },
    {
      name: "Rejected",
    },
    {
      name: "Completed",
    },
  ],
  EXPENSE_STATUS: [
    {
      name: "Pending",
    },
    {
      name: "Pending",
    },
    {
      name: "Rejected",
    },
    {
      name: "Draft",
    },
  ],
  INVOICE_STATUS: [
    {
      name: "Approved for payment",
    },
    {
      name: "Approved",
    },
    {
      name: "Rejected",
    },
    {
      name: "Paid",
    },
    {
      name: "Pending",
    },
    {
      name: "Draft",
    },
  ],
};
